version: '3'
# "Composefile"のバージョン
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: rails5_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
  web:
    build: .
    container_name: rails5_web
    volumes:
      - .:/usr/src/
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      BINDING: 0.0.0.0
    stdin_open: true
    tty: true

volumes:
  mysql_data: